# Numpy Arrays 
date: 2018/10/03  
author: kyoko k <kuskyoko@gmail.com>  

In [3]:
mlist = [1,2,3]
mlist

[1, 2, 3]

In [5]:
import numpy as np

In [7]:
arr = np.array(mlist)

In [8]:
arr

array([1, 2, 3])

In [10]:
m_mat = [[1,2,3], [4,5,6], [7,8,9]]
m_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(m_mat) #　[[]]→matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 10)　# 0-10 までstepだけ等差な数列を返す a range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0, 10, 2.0) # stepがfloatかintか

array([0., 2., 4., 6., 8.])

In [21]:
np.zeros(3) #float

array([0., 0., 0.])

In [22]:
np.zeros((2,3)) #float

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3,4)) # float

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0, 5, 20) #0-5まで20個の等差数列の値を返す　[]はひとつ→vector

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [26]:
np.eye(4) #単位行列　identity matrix -> eye　float

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(5) #一様分布, 0-1の小数乱数

array([0.92687143, 0.90880198, 0.07850136, 0.34258933, 0.58768732])

In [29]:
np.random.randn(5, 5) #正規分布, 小数乱数 

array([[-0.88119881, -1.16836557, -1.41892518, -0.92968432,  0.06476234],
       [-2.78405604,  0.79325132, -1.50570885,  0.31620415, -0.19123943],
       [ 0.06849669, -1.38100442, -0.67210903, -1.16366545, -0.60235176],
       [-0.40070369,  1.07028028,  0.33702661,  3.01540951, -1.17654674],
       [-1.02138745,  0.63979902,  1.0234771 ,  0.95593952,  1.00509053]])

In [35]:
np.random.randint(1,100,10) #10つだけ1~99の乱数を生成

array([ 1, 24, 66, 54, 26, 98, 36, 76, 23, 27])

In [36]:
arr = np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
ranarr = np.random.randint(0, 50, 10)

In [39]:
ranarr

array([29, 42, 49, 19, 40,  4,  7,  8, 10, 28])

In [40]:
arr.reshape(5,5) #5*5のmatrixにvectorから変形

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr.max()

49

In [43]:
ranarr.min()

4

In [44]:
ranarr

array([29, 42, 49, 19, 40,  4,  7,  8, 10, 28])

In [46]:
ranarr.argmax() #maxのindexを返す

2

In [47]:
arr.shape

(25,)

In [48]:
arr = arr.reshape(5,5)

In [49]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr.shape #shape は method でなく property

(5, 5)

In [53]:
arr.dtype # property return datatype of vector or matrix

dtype('int64')

In [54]:
from numpy.random import randint # np. を省略する方法

In [55]:
randint(1,10)

4